### ISSUE TITLE
Dragon move bugs

### ISSUE THREAD

**Issue by andriikovalov** [lords-web-game/lords#203]
- [x] Different cursors to move close and far
![dr1](https://user-images.githubusercontent.com/19880058/47169475-f09d3f80-d303-11e8-8fb2-3af742f42893.png)
![dr2](https://user-images.githubusercontent.com/19880058/47169476-f09d3f80-d303-11e8-801a-fb7ab9de654a.png)

- [ ] Can't point dragon to move to certain places (NE, E or SE, SE)
![dr3](https://user-images.githubusercontent.com/19880058/47169477-f09d3f80-d303-11e8-8b12-a3fecaa71ccf.png)

- [x] Flight path finding doesn't work below
![dr4](https://user-images.githubusercontent.com/19880058/47169993-41f9fe80-d305-11e8-84d9-14c313d4ca52.png)

**Comment by sergey-koba-mobidev** [comment]
1) agreed - bug
2) You are pointing to the cell so that dragon would partially stand on the water. For me it works as expected.
3) What is the expected result? what is wrong in other words? :D

**Comment by andriikovalov** [comment]
2. What I mean it that is not possible to move a dragon SE,SE in one click. Similarly to NE,E - it's either NE or NE,E,E
3. I would expect the dragon to fly over trees to the cell under mouse cursor (5 moves)

**Comment by sergey-koba-mobidev** [comment]
@andriikovalov I fixed everything except 2.
Because in order to move 1 SE you cant point top left coord, it would be dragon itself. So you need to point one coord SE more to make 1 move. So I cant figure out you want to make 1 move SE or 2 SE. I think this is ok as it is now and as it was all this time working.
